# Generated by Django 4.2.6 on 2023-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0009_auto_20230922_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('Location', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('veg', 'veg'), ('Non-veg', 'Non-veg')], max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='places',
            old_name='pimage',
            new_name='image',
        ),
        migrations.AddField(
            model_name='places',
            name='image1',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='image2',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
